services:
  acme_operador:
    build:
      context: .
      dockerfile: acme_operador.Dockerfile
    container_name: acme_operador
    networks:
      - acmenet
    hostname: acme.operador
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    environment:
      - SIP_DOMAIN=acme.operador
      - WITH_KEMI=python
    volumes:
      - ./config/kamailio.cfg:/etc/kamailio/kamailio.cfg:ro
      - ./src/redial_service.py:/etc/kamailio/redial_service.py:ro
      - kamailio_socket:/var/run/kamailio # expose socket for kpi agent access
    user: root
    command: >
      sh -c "mkdir -p /var/run/kamailio && chown kamailio:kamailio /var/run/kamailio && /usr/sbin/kamailio -DD -E -f /etc/kamailio/kamailio.cfg"
    restart: unless-stopped

  acme_gnmi:
    image: acme_operador:latest
    build:
      context: .
      dockerfile: acme_operador.Dockerfile
    container_name: acme_gnmi
    networks:
      - acmenet
    volumes:
      - kamailio_socket:/var/run/kamailio # mnt volume for socket access on SIP server
      - ./src/gnmi_agent.py:/gnmi_agent.py
    user: root
    depends_on:
      - acme_operador
    command: /usr/bin/python3 /gnmi_agent.py

  acme_terminal:
    image: rodrigolf80/igrs_terminal:latest
    container_name: acme_terminal
    networks:
      - acmenet
    hostname: acme.terminal
    environment:
      - DISPLAY=host.docker.internal:0
    ports:
      - "5900:5900"
    depends_on:
      - acme_operador
    restart: unless-stopped

networks:
  acmenet:
    driver: bridge

volumes:
  kamailio_socket:
