services:
  acme_operador:
    build:
      context: .
      dockerfile: acme_operador.Dockerfile
    container_name: acme_operador
    networks:
      - acmenet
    hostname: acme.operador
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    environment:
      - SIP_DOMAIN=acme.operador
      - WITH_KEMI=python
    volumes:
      - ./config/kamailio.cfg:/etc/kamailio/kamailio.cfg:ro
      #- ./src/redial_service.py:/etc/kamailio/redial_service.py:ro
    command: /usr/sbin/kamailio -DD -E -f /etc/kamailio/kamailio.cfg
    restart: unless-stopped

  acme_terminal:
    image: rodrigolf80/igrs:05
    container_name: acme_terminal
    networks:
      - acmenet
    hostname: acme.terminal
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - "5900:5900"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ipc: host
    privileged: true
    depends_on:
      - acme_operador
    restart: unless-stopped

networks:
  acmenet:
    driver: bridge
