services:
  acme_operador:
    build:
      context: .
      dockerfile: acme_operador.Dockerfile
    container_name: acme_operador
    networks:
      - acmenet
    hostname: acme.operador
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5080:8080"
    environment:
      - SIP_DOMAIN=acme.operador
      - DB_HOST=acme_db
      - POSTGRES_USER=kamailio
      - POSTGRES_PASSWORD=kamailiopw
      - POSTGRES_DB=kamailio
      - WITH_DB=yes
      - DB_URL=postgres://kamailio:kamailiopw@acme_db:5432/kamailio
      - WITH_KEMI=python
    volumes:
      - ./config/kamailio.cfg:/etc/kamailio/kamailio.cfg:ro
      - ./src/redial_service.py:/etc/kamailio/redial_service.py:ro
    command: /usr/sbin/kamailio -DD -E -f /etc/kamailio/kamailio.cfg
    depends_on:
      - acme_db
    restart: unless-stopped

  acme_db:
    image: postgres:15-alpine
    container_name: acme_db
    networks:
      - acmenet
    hostname: acme.db
    environment:
      - DB_HOST=acme_db
      - POSTGRES_USER=kamailio
      - POSTGRES_PASSWORD=kamailiopw
      - POSTGRES_DB=kamailio
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  acme_terminal:
    image: rodrigolf80/igrs:04
    container_name: acme_terminal
    networks:
      - acmenet
    hostname: acme.terminal
    environment:
      - DISPLAY=$DISPLAY
    ports:
      - "5900:5900"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ipc: host
    privileged: true
    depends_on:
      - acme_operador
    restart: unless-stopped

networks:
  acmenet:
    driver: bridge

volumes:
  db_data:
