services:
  # Kamailio SIP Server for the 'acme.operador' domain
  kamailio_acme:
    build:
      context: .
      dockerfile: kamailio_acme.Dockerfile
    container_name: kamailio_acme
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8080:8080"
    networks:
      - sipnet
    hostname: acme.operador
    environment:
      - SIP_DOMAIN=acme.operador
      - WITH_DB=yes
      - DB_URL=${DB_URL} 
      #- DB_URL=postgres://kamailio:kamailiopw@db_acme/kamailio
      - WITH_KEMI=python
    volumes:
      - ./config/kamailio.cfg:/etc/kamailio/kamailio.cfg:ro
      - ./scripts/redial_service.py:/etc/kamailio/redial_service.py:ro
    depends_on:
      - db_acme
    restart: unless-stopped

  # PostgreSQL Database for Registration and Service Data
  db_acme:
    image: postgres:15-alpine
    container_name: db_acme
    networks:
      - sipnet
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      #- POSTGRES_USER=kamailio
      #- POSTGRES_PASSWORD=kamailiopw
      #- POSTGRES_DB=kamailio
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Terminal
  terminal:
    image: igrs_grlt:04
    container_name: terminal
    hostname: sipnet.terminal
    environment:
      - DISPLAY=$DISPLAY
    networks:
      - sipnet
    ports:
      - "5900:5900"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ipc: host
    privileged: true
    depends_on:
      - kamailio_acme
    restart: unless-stopped

networks:
  sipnet:
    driver: bridge

volumes:
  db_data:
